<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFramework>net6.0</TargetFramework>
		<ImplicitUsings>disable</ImplicitUsings>
		<Nullable>enable</Nullable>
		<AllowUnsafeBlocks>true</AllowUnsafeBlocks>
		<GenerateDocumentationFile>True</GenerateDocumentationFile>
	</PropertyGroup>

	<PropertyGroup>
		<AssetsFileDir>../Assets/</AssetsFileDir>
		<PluginOutputPath>../output/Hikaria.QuantumConsole/plugins/</PluginOutputPath>
		<LocalizationFileDir>../Localization/</LocalizationFileDir>
		<CopyBuildToPluginFolder>true</CopyBuildToPluginFolder>
	</PropertyGroup>

	<Import Project="../Dependencies.props" />
	<Import Project="../DefineConstants.props" />

</Project>
