<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFramework>net6.0</TargetFramework>
		<ImplicitUsings>disable</ImplicitUsings>
		<Nullable>enable</Nullable>
		<AllowUnsafeBlocks>true</AllowUnsafeBlocks>
		<GenerateDocumentationFile>True</GenerateDocumentationFile>
	</PropertyGroup>

	<Import Project="../Dependencies.props" />
	<Import Project="../DefineConstants.props" />

</Project>
