<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net6.0</TargetFramework>
    <ImplicitUsings>disable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

	<Import Project="../Dependencies.props" />
	<Import Project="../DefineConstants.props" />

	<ItemGroup>
	  <ProjectReference Include="..\Hikaria.QC\Hikaria.QC.csproj" />
	</ItemGroup>

</Project>
